name: Testing CD using github actions
on: push
jobs:
    make-svelte-app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Build and move from dist to root
              run: |
                  rm -rf assets index.html *.webp
                  cd source-code/
                  npm i
                  npm run build
                  sudo mv dist/* ../
                  rm -rf dist node_modules

            - name: Commit files
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add .
                  git commit -m "Deployment building through automated changes by Hetarth Shah using Github Actions"
                  git push
