name: Testing CD using github actions
on: push
jobs:
    make-svelte-app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Build and move from dist to root
              run: |
                  cd source-code/
                  npm i
                  npm run build
                  sudo mv dist/* ./
            - name: Commit files
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git commit -m "Add changes" -a
            - name: Push changes
              uses: ad-m/github-push-action@master
