name: Testing CD using github actions
on: push
jobs:
  make-svelte-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: NPM Install
        run: npm i

      - name: Build and move from dist to deploy folder
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          npm run build
          mkdir deploy
          ls
          mv dist/* deploy/
