name: Testing CD using github actions
on: push
jobs:
    make-svelte-app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Build and move from dist to root
              run: |
                  ls
                  cd source-code/
                  ls
                  npm i
                  ls
                  npm run build
                  ls
                  ls ./
                  ls ../
                  # sudo mv dist/* ../
            # - name: Commit files
            #   run: |
            #       git add .
            #       git commit -m "Add changes"
            #       git push
